name: "Setup AWS Infra"

on:
  push:
  workflow_dispatch:

jobs:
  setup-infra:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install powershell dependencies
        shell: pwsh
        run: |
          Install-Module -Name AWSPowerShell.NetCore -Force -SkipPublisherCheck -AllowClobber -Scope AllUsers