name: "Setup AWS Infra"

on:
  push:
  workflow_dispatch:

jobs:
  setup-infra:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install powershell dependencies
        run: |
          pwsh -Command "Install-Module -Name AWSPowerShell.NetCore -Force -SkipPublisherCheck -AllowClobber -Scope CurrentUser"

      - name: autheticate AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ${{vars.AWS_REGION}}
      
      - name: create backend
        shell: pwsh
        run: |
          cd ./scripts
          ./create-backend.ps1 -bucketName "s3_state_bucket" -dynamoDb "s3_lock_table" -region "us-west-2" 